// Code generated by protoc-gen-go.
// source: Person.proto
// DO NOT EDIT!

/*
Package Person is a generated protocol buffer package.

It is generated from these files:
	Person.proto

It has these top-level messages:
	Person2
*/
package Person2

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Person2_PhoneType int32

const (
	Person2_MOBILE Person2_PhoneType = 0
	Person2_HOME   Person2_PhoneType = 1
	Person2_WORK   Person2_PhoneType = 2
)

var Person2_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person2_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person2_PhoneType) Enum() *Person2_PhoneType {
	p := new(Person2_PhoneType)
	*p = x
	return p
}
func (x Person2_PhoneType) String() string {
	return proto.EnumName(Person2_PhoneType_name, int32(x))
}
func (x *Person2_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person2_PhoneType_value, data, "Person2_PhoneType")
	if err != nil {
		return err
	}
	*x = Person2_PhoneType(value)
	return nil
}

type Person2 struct {
	Name             *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32                 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Email2           *string                `protobuf:"bytes,5,opt,name=email2" json:"email2,omitempty"`
	Phone            []*Person2_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Person2) Reset()         { *m = Person2{} }
func (m *Person2) String() string { return proto.CompactTextString(m) }
func (*Person2) ProtoMessage()    {}

func (m *Person2) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person2) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person2) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person2) GetEmail2() string {
	if m != nil && m.Email2 != nil {
		return *m.Email2
	}
	return ""
}

func (m *Person2) GetPhone() []*Person2_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type Person2_PhoneNumber struct {
	Number           *string            `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person2_PhoneType `protobuf:"varint,2,opt,name=type,enum=Person2_PhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Person2_PhoneNumber) Reset()         { *m = Person2_PhoneNumber{} }
func (m *Person2_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person2_PhoneNumber) ProtoMessage()    {}

const Default_Person2_PhoneNumber_Type Person2_PhoneType = Person2_HOME

func (m *Person2_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person2_PhoneNumber) GetType() Person2_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Person2_PhoneNumber_Type
}

func init() {
	proto.RegisterEnum("Person2_PhoneType", Person2_PhoneType_name, Person2_PhoneType_value)
}
